name: Deploy

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  copy:
    name: Copy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: copy file via ssh password
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        source: "./"
        target: "./bots/jessica-tmp"
  deploy:
    name: "Deploy the latest files"
    runs-on: ubuntu-latest
    needs: copy
    steps:
    - name: "executing remote ssh commands"
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        script: |
          sudo pm2 delete jessica
          cp -r -f ./bots/jessica-tmp/* ./bots/jessica/
          rm -r bots/jessica-tmp
          cd bots/jessica
          source venv/bin/activate
          pip install -r requirements.txt
          sudo pm2 start jessica.py --no-autorestart --interpreter $(pwd)/venv/bin/python
          sudo pm2 startup systemd
          sudo pm2 save
